---
- name: Install release package
  apt:
    deb: https://github.com/AlexAkulov/clickhouse-backup/releases/download/v{{ clickhouse_backup_version }}/clickhouse-backup_{{ clickhouse_backup_version }}_amd64.deb
